server:
  port: 9000

spring:
  application:
    name: "cards"
  profiles:
    active: "qa"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"


#  config:
#    import:
#      - "application_qa.yml"
#      - "application_prod.yml"
#  profiles:
#    active:
#        - "qa"  # enter profile you want to activate
#
#build:
#  version: "1.0dev"
#
#cards:
#  message: "Welcome to Cards Related local API's"
#  contactDetails:
#    name: "Jay Pande - Developer"
#    email: "jmaypande@gmail.com"
#  support:
#      - (+91) 7351733644